"""empty message

Revision ID: 2fc960e26135
Revises: 9e49093ee602
Create Date: 2025-05-15 18:50:05.259908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc960e26135'
down_revision = '9e49093ee602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('n_rows',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('n_columns',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_constraint('unique_share', type_='unique')

    with op.batch_alter_table('visualisation', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualisation', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_share', ['owner_id', 'target_id', 'object_type', 'object_id'])

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('n_columns',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('n_rows',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
